/**
 * EWD DB interface
 * This is a prototype server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: praneethmendu@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Machine { 
    customerId: number;
    customerName?: string;
    machineNr?: string;
    machineId?: number;
    machineTypeSerial?: string;
    process?: string;
    processTime?: string;
    sensorData?: string;
    onlineFrom?: string;
}

export interface MachineQueryParams {
    customer?: string;
    drainSensorOn?: boolean;
    pump5On?:boolean;
    pump10On?:boolean;
    waterTemp?:ContinuousValue;
    waterLevel?:ContinuousValue;
}

export interface ContinuousValue {
    eq?: number;
    lt?: number;
    gt?: number;
}